services:
  - type: web
    name: prediction-abandon-scolaire
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 